version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - "9090:80"
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: brandsofmedia
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8090:80"
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
    mailhog:
      image: mailhog/mailhog:v1.0.0
      ports:
        - "1025:1025"
        - "8025:8025"
  
    